# Exported from:        http://xl-release-nightly.xebialabs.com:5516/
# Release version:      24.3.0-1014.113
# Date created:         Mon Oct 14 13:43:12 CEST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_1.yaml
